UPDATE PUBLIC.CATEGORY SET NAME = 'Washing Machines' WHERE ID = 0;
UPDATE PUBLIC.CATEGORY SET NAME = 'Electric Shavers' WHERE ID = 1;
UPDATE PUBLIC.CATEGORY SET NAME = 'Fridges' WHERE ID = 2;
UPDATE PUBLIC.CATEGORY SET NAME = 'Laptops' WHERE ID = 3;
UPDATE PUBLIC.CATEGORY SET NAME = 'Rice Cookers' WHERE ID = 4;
UPDATE PUBLIC.CATEGORY SET NAME = 'Videocameras' WHERE ID = 5;
UPDATE PUBLIC.CATEGORY SET NAME = 'Tvs' WHERE ID = 6;
UPDATE PUBLIC.CATEGORY SET NAME = 'Wearables' WHERE ID = 7;