INSERT INTO PUBLIC.CATEGORY (ID, NAME) VALUES (0, 'Washing Machines');
INSERT INTO PUBLIC.CATEGORY (ID, NAME) VALUES (1, 'Electric Shavers');
INSERT INTO PUBLIC.CATEGORY (ID, NAME) VALUES (2, 'Fridges');
INSERT INTO PUBLIC.CATEGORY (ID, NAME) VALUES (3, 'Laptops');
INSERT INTO PUBLIC.CATEGORY (ID, NAME) VALUES (4, 'Rice Cookers');
INSERT INTO PUBLIC.CATEGORY (ID, NAME) VALUES (5, 'Videocameras');
INSERT INTO PUBLIC.CATEGORY (ID, NAME) VALUES (6, 'Tvs');
INSERT INTO PUBLIC.CATEGORY (ID, NAME) VALUES (7, 'Wearables');